### ISSUE TITLE
Add Game Rules

### ISSUE THREAD

**Issue by jathurchan** [jathurchan/TurnBasedCombatCpp#3]
## First steps
- [x] Pull the branch *dev*: `git pull remote dev`
- [x] Change to the branch *dev*: `git checkout dev`
- [x] Create a new local branch : `git checkout -b dev-rules`
- [x] `cd docs`
- [x] Add *game-rules.md*
## Game Rules
- [x] Write game rules in English
## Final steps
- [x] Add files and commit changes
- [x] Push it to remote: `git push origin dev`
- [x] Create a pull request on GitHub to merge the feature branch *res* to *dev* (base)
- [x] Delete the branch once merge completed

**Comment by jathurchan** [comment]
Hey @akossyfidis , I thought it could be great if our game rules document followed a similar structure to this document:
[Game Rules](https://assets.pokemon.com/assets/cms2/pdf/trading-card-game/rulebook/swsh10_rulebook_en.pdf).

What do you think? 😇

**Comment by akossyfidis** [comment]
It is such a good idea, I'm on it.
