### ISSUE TITLE
Update GenerateDiaHeader

### ISSUE THREAD

**Issue by Gzethicus** [jathurchan/TurnBasedCombatCpp#4]
In cmake/GenerateDiaHeader.cmake
- [x] l.9-10-35-36 : add "pp" at the end of each line
- [ ] l. 37 : command $<target_file:dia2code> [...] -d{$output_dir} <ins>**-ext hpp**</ins> -t cpp [...]

**Comment by jathurchan** [comment]
I think the second modification is not needed. Actually the modifier -ext does not even exists 😅

**Comment by NiskuT** [comment]
@jathurchan Actually -ext exist in your dia2code, you can find information about it in [dia2code/main.c](https://github.com/jathurchan/TurnBasedCombatCpp/blob/ace0e85ef8f04d9e12ee757f43df413ec8e318d1/dependencies/dia2code/src/main.c#L115) and it is retrieve [line 173](https://github.com/jathurchan/TurnBasedCombatCpp/blob/ace0e85ef8f04d9e12ee757f43df413ec8e318d1/dependencies/dia2code/src/main.c#L173) ;-)
